# Docs changes
Documentation:
- any:
  - changed-files:
    - any-glob-to-any-file: ['doc/*', '*.md']

# Add 'meta' label to any root file changes
meta:
- any:
  - changed-files:
    - any-glob-to-any-file: ['*', '.github/*']

# Add 'C' label to any change within the 'C' code base
C:
- any:
  - changed-files:
    - any-glob-to-any-file: ['src/api/c/*', 'src/api/c/**/*']

C++:
- any:
  - changed-files:
    - any-glob-to-any-file: ['src/api/cpp/*', 'src/api/cpp/**/*']

Java:
- any:
  - changed-files:
    - any-glob-to-any-file: ['src/api/java/*', 'src/api/java/**/*']

JavaScript:
- any:
  - changed-files:
    - any-glob-to-any-file: ['src/api/js/*', 'src/api/js/**/*']

WebServices:
- any:
  - changed-files:
    - any-glob-to-any-file: ['src/api/js/*', 'src/api/js/**/*']

python:
- any:
  - changed-files:
    - any-glob-to-any-file: ['src/api/python/*', 'src/api/python/**/*']

CI:
- any:
  - changed-files:
    - any-glob-to-any-file: ['tools/ci/*']

# Add 'dependencies' label to any change in lib
dependencies:
- any: ['lib/**/*']
- any: ['src/scripts/build.sh']
- any: ['src/scripts/dependencies/*/**']
