# Add 'meta' label to any root file changes
meta:
- any: ['*', '.github/*']

# Add '@domain/core' label to any change within the 'core' package
C:
- any: ['src/api/c/*', 'src/api/c/**/*']

C++:
- any: ['src/api/cpp/*', 'src/api/cpp/**/*']

Java:
- any: ['src/api/java/*', 'src/api/java/**/*']

JavaScript:
- any: ['src/api/js/*', 'src/api/js/**/*']

WebServices:
- any: ['src/api/js/*', 'src/api/js/**/*']

python:
- any: ['src/api/python/*', 'src/api/python/**/*']

CI:
- any: ['tools/ci/*']

# Add 'source' label to any change to src files within the source dir EXCEPT for the docs sub-folder
#source:
#- any: ['src/**/*', '!docs/*']

# Add 'dependencies' label to any change in lib
dependencies:
- any: ['lib/**/*']
- any: ['src/scripts/build.sh']
- any: ['src/scripts/dependencies/*/**']
