// A placeholder for OpenISS Skeleton related enumerations.

#ifndef OISkeletonEnums_hpp
#define OISkeletonEnums_hpp

enum class OISKELETON_JOINT_TYPES
{
//
    OISKELETON_JOINT_HEAD,
    OISKELETON_JOINT_NECK,
//
    OISKELETON_JOINT_LEFT_SHOULDER,
    OISKELETON_JOINT_RIGHT_SHOULDER,
    OISKELETON_JOINT_LEFT_ELBOW,
    OISKELETON_JOINT_RIGHT_ELBOW,
    OISKELETON_JOINT_LEFT_HAND,
    OISKELETON_JOINT_RIGHT_HAND,
//
    OISKELETON_JOINT_TORSO,
//
    OISKELETON_JOINT_LEFT_HIP,
    OISKELETON_JOINT_RIGHT_HIP,
    OISKELETON_JOINT_LEFT_KNEE,
    OISKELETON_JOINT_RIGHT_KNEE,
    OISKELETON_JOINT_LEFT_FOOT,
    OISKELETON_JOINT_RIGHT_FOOT,

};

#endif /* OISkeletonEnums_hpp */